### ISSUE TITLE
File opens already folded

### ISSUE THREAD

**Issue by gilfuser** [digitalrounin/vim-yaml-folds#6]
Hi!

Thank you for your work on this plugin. Yaml is cool and is super useful to being able to fold it the way this plugin does it.

I'm having a minor issue with it though. Whenever I open a .yml file, it comes already folded. Is there a way to change this behaviour?

I'm using neovim b.t.w.

If any info could help tracking this issue down, please ask.

best regards,
Gil

**Comment by benjyiw** [comment]
there's a few ways to go about that.

you can unfold all folds in yaml files automatically with something like this in your rc file:
```
au BufRead *.yml normal zR
au BufRead *.yaml normal zR
```

or disable folding all together with
```
set nofoldenable
```

**Comment by gilfuser** [comment]
Thank you!

This solves the problem.
It would be nice if it was documented.
